pages:
  image: node:6
  stage: deploy
  cache:
    paths:
      - node_modules/
  script:
    - npm install vue-material@beta --save
    - cd node_modules
    - git clone -b firestore https://github.com/vuejs/vuefire.git
    - cd vuefire
    - npm install
    - npm run build
    - cd ../../
    - npm install
    - npm run build
    - mkdir public
    - mv dist/* public
  artifacts:
    paths:
      - public
  only:
  - master
