pages:
  image: node:alpine
  stage: deploy
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
    - mkdir public
    - mv dist/* public
  artifacts:
    paths:
      - public
  only:
  - master
