pages:
  image: node:6
  stage: build
  script:
    - npm install vue-material@beta --save
    - npm i vuefire@next
    - npm install
    - npm run build
  artifacts:
    paths:
      - static
  only:
  - master
